import type { SupportCardType } from '../types';

export interface SupportCard {
    id: string;
    name: string;
    type: SupportCardType;
    rarity: 'SSR' | 'SR' | 'R';
    cardName: string;
}

export const SUPPORT_CARD_DICT: Record<string, SupportCard> = {
    'admire-vega-power':        { id: 'admire-vega-power',     name: 'Admire Vega',  cardName: 'Lucky Star In The Sky',                               type: 'power',   rarity: 'SSR' },
    'agnes-digital-power':      { id: 'agnes-digital-power',      name: 'Agnes Digital',      cardName: 'A Fan\'s Joy',                                               type: 'power',   rarity: 'SSR' },
    'air-shakur-wit':           { id: 'air-shakur-wit',           name: 'Air Shakur',         cardName: '7 Centimeters Ahead',                                        type: 'wit',     rarity: 'SSR' },
    'bamboo-memory-power':      { id: 'bamboo-memory-power',      name: 'Bamboo Memory',      cardName: 'Head-on Fight!',                                             type: 'power',   rarity: 'SSR' },
    'curren-chan-wit':           { id: 'curren-chan-wit',           name: 'Curren Chan',        cardName: 'Cutie Pie with Shining Eyes',                                type: 'wit',     rarity: 'SSR' },
    'daitaku-helios-power':     { id: 'daitaku-helios-power',      name: 'Daitaku Helios',     cardName: 'Make! Some! NOISE!',                                         type: 'power',   rarity: 'SSR' },
    'biko-pegasus-speed':       { id: 'biko-pegasus-speed',       name: 'Biko Pegasus',       cardName: 'Double Carrot Punch!',                                       type: 'speed',   rarity: 'SSR' },
    'daiwa-scarlet-power':      { id: 'daiwa-scarlet-power',      name: 'Daiwa Scarlet',      cardName: 'Mini☆Vacation',                                              type: 'power',   rarity: 'SSR' },
    'el-condor-pasa-power':     { id: 'el-condor-pasa-power',     name: 'El Condor Pasa',     cardName: 'Champion\'s Passion',                                        type: 'power',   rarity: 'SSR' },
    'fine-motion-wit':          { id: 'fine-motion-wit',          name: 'Fine Motion',        cardName: 'Wave of Gratitude',                                          type: 'wit',     rarity: 'SSR' },
    'gold-city-speed':          { id: 'gold-city-speed',          name: 'Gold City',          cardName: 'Run(my)way',                                                 type: 'speed',   rarity: 'SSR' },
    'gold-ship-stamina':        { id: 'gold-ship-stamina',        name: 'Gold Ship',          cardName: 'Breakaway Battleship',                                       type: 'stamina', rarity: 'SSR' },
    'gold-ship-speed':          { id: 'gold-ship-speed',          name: 'Gold Ship',          cardName: 'That Time I Became The Strongest',                           type: 'speed',   rarity: 'SSR' },
    'grass-wonder-guts':        { id: 'grass-wonder-guts',        name: 'Grass Wonder',       cardName: 'Fairest Fleur',                                              type: 'guts',    rarity: 'SSR' },
    'haru-urara-guts':          { id: 'haru-urara-guts',          name: 'Haru Urara',         cardName: 'Urara\'s Day Off!',                                          type: 'guts',    rarity: 'SSR' },
    'hishi-akebono-guts':       { id: 'hishi-akebono-guts',       name: 'Hishi Akebono',      cardName: 'Who Wants the First Bite?',                                  type: 'guts',    rarity: 'SSR' },
    'ikuno-dictus-guts':        { id: 'ikuno-dictus-guts',        name: 'Ikuno Dictus',       cardName: 'Warm Heart, Soft Steps',                                     type: 'guts',    rarity: 'SSR' },
    'ines-fujin-guts':          { id: 'ines-fujin-guts',          name: 'Ines Fujin',         cardName: 'Watch My Star Fly!',                                         type: 'guts',    rarity: 'SSR' },
    'kawakami-princess-speed':  { id: 'kawakami-princess-speed',  name: 'Kawakami Princess',  cardName: 'Princess Bride',                                             type: 'speed',   rarity: 'SSR' },
    'manhattan-cafe-stamina':   { id: 'manhattan-cafe-stamina',   name: 'Manhattan Cafe',     cardName: 'My Solo Spun in Spiraling Runs',                             type: 'stamina', rarity: 'SSR' },
    'marvelous-sunday-power':   { id: 'marvelous-sunday-power',   name: 'Marvelous Sunday',   cardName: 'Dazzling Day in the Snow',                                   type: 'power',   rarity: 'SSR' },
    'mayano-top-gun-speed':     { id: 'mayano-top-gun-speed',     name: 'Mayano Top Gun',     cardName: 'Party Formation',                                            type: 'speed',   rarity: 'SSR' },
    'king-halo-power':          { id: 'king-halo-power',          name: 'King Halo',          cardName: 'Tonight, We Waltz',                                          type: 'power',   rarity: 'SSR' },
    'kitasan-black-speed':      { id: 'kitasan-black-speed',      name: 'Kitasan Black',      cardName: 'Fire at My Heels!',                                          type: 'speed',   rarity: 'SSR' },
    'matikanefukukitaru-speed':  { id: 'matikanefukukitaru-speed',  name: 'Matikanefukukitaru', cardName: 'Touching Sleeves Is Good Luck!♪',                          type: 'speed',   rarity: 'SSR' },
    'matikanetannhauser-guts':  { id: 'matikanetannhauser-guts',  name: 'Matikanetannhauser', cardName: 'Just Keep Going',                                            type: 'guts',    rarity: 'SSR' },
    'meisho-doto-stamina':   { id: 'meisho-doto-stamina',   name: 'Meisho Doto',     cardName: 'Leaping Into The Unknown',                                              type: 'stamina', rarity: 'SSR' },
    'mejiro-bright-stamina':    { id: 'mejiro-bright-stamina',    name: 'Mejiro Bright',      cardName: 'Little by Little',                                           type: 'stamina', rarity: 'SSR' },
    'mejiro-dober-wit':         { id: 'mejiro-dober-wit',         name: 'Mejiro Dober',       cardName: 'My Thoughts, My Desires',                                    type: 'wit',     rarity: 'SSR' },
    'mejiro-mcqueen-stamina':   { id: 'mejiro-mcqueen-stamina',   name: 'Mejiro McQueen',     cardName: 'Your Team Ace',                                              type: 'stamina', rarity: 'SSR' },
    'mejiro-palmer-guts':       { id: 'mejiro-palmer-guts',       name: 'Mejiro Palmer',      cardName: 'Go Ahead and Laugh',                                         type: 'guts',    rarity: 'SSR' },
    'mejiro-ryan-guts':         { id: 'mejiro-ryan-guts',         name: 'Mejiro Ryan',        cardName: 'Winning Pitch',                                              type: 'guts',    rarity: 'SSR' },
    'mihono-bourbon-wit':       { id: 'mihono-bourbon-wit',       name: 'Mihono Bourbon',     cardName: 'The Ghost Finds Halloween Magic',                            type: 'wit',     rarity: 'SSR' },
    'nakayama-festa-stamina':   { id: 'nakayama-festa-stamina',   name: 'Nakayama Festa',     cardName: '43, 8, 1',                                                   type: 'stamina', rarity: 'SSR' },
    'narita-brian-stamina':     { id: 'narita-brian-stamina',     name: 'Narita Brian',       cardName: 'The Whistling Arrow\'s Taunt',                               type: 'stamina', rarity: 'SSR' },
    'narita-brian-speed':       { id: 'narita-brian-speed',       name: 'Narita Brian',       cardName: 'Two Pieces',                                                 type: 'speed',   rarity: 'SSR' },
    'narita-taishin-wit':       { id: 'narita-taishin-wit',       name: 'Narita Taishin',     cardName: 'Strict Shopper',                                             type: 'wit',     rarity: 'SSR' },
    'narita-top-road-speed':    { id: 'narita-top-road-speed',    name: 'Narita Top Road',    cardName: 'Peachy Silhouette',                                          type: 'speed',   rarity: 'SSR' },
    'nice-nature-wit':          { id: 'nice-nature-wit',          name: 'Nice Nature',        cardName: 'Daring to Dream',                                            type: 'wit',     rarity: 'SSR' },
    'nishino-flower-wit':       { id: 'nishino-flower-wit',       name: 'Nishino Flower',     cardName: 'Little Cupcakes, Big Emotions',                              type: 'wit',     rarity: 'SSR' },
    'nishino-flower-speed':     { id: 'nishino-flower-speed',     name: 'Nishino Flower',     cardName: 'Even the Littlest Bud',                                      type: 'speed',   rarity: 'SSR' },
    'oguri-cap-power':          { id: 'oguri-cap-power',          name: 'Oguri Cap',          cardName: 'Get Lots of Hugs for Me',                                    type: 'power',   rarity: 'SSR' },
    'rice-shower-stamina':      { id: 'rice-shower-stamina',      name: 'Rice Shower',        cardName: 'Showered In Joy',                                            type: 'stamina', rarity: 'SSR' },
    'rice-shower-power':        { id: 'rice-shower-power',        name: 'Rice Shower',        cardName: 'Happiness Just around the Bend',                             type: 'power',   rarity: 'SSR' },
    'riko-kashimoto-pal':       { id: 'riko-kashimoto-pal',       name: 'Riko Kashimoto',     cardName: 'Planned Perfection',                                         type: 'pal',     rarity: 'SSR' },
    'sakura-bakushin-o-guts':   { id: 'sakura-bakushin-o-guts',   name: 'Sakura Bakushin O',  cardName: 'Super! Sonic! Flower Power!',                                type: 'guts',    rarity: 'SSR' },
    'sakura-bakushin-o-speed':  { id: 'sakura-bakushin-o-speed',  name: 'Sakura Bakushin O',  cardName: 'Eat Fast! Yum Fast!',                                        type: 'speed',   rarity: 'SSR' },
    'sakura-chiyono-o-stamina': { id: 'sakura-chiyono-o-stamina', name: 'Sakura Chiyono O',   cardName: 'Peak Sakura Season',                                         type: 'stamina', rarity: 'SSR' },
    'sasami-anshinzawa-pal':    { id: 'sasami-anshinzawa-pal',    name: 'Sasami Anshinzawa',  cardName: 'This Might Sting!',                                          type: 'pal',     rarity: 'SSR' },
    'satono-diamond-wit':       { id: 'satono-diamond-wit',       name: 'Satono Diamond',     cardName: 'Special Dreamers!',                                          type: 'wit',     rarity: 'SSR' },
    'satono-diamond-stamina':   { id: 'satono-diamond-stamina',   name: 'Satono Diamond',     cardName: 'The Will to Overtake',                                       type: 'stamina', rarity: 'SSR' },
    'seiun-sky-stamina':        { id: 'seiun-sky-stamina',        name: 'Seiun Sky',          cardName: 'Foolproof Plan',                                             type: 'stamina', rarity: 'SSR' },
    'seiun-sky-wit':            { id: 'seiun-sky-wit',            name: 'Seiun Sky',          cardName: 'Paint the Sky Red',                                          type: 'wit',     rarity: 'SSR' },
    'silence-suzuka-speed-2':   { id: 'silence-suzuka-speed-2',   name: 'Silence Suzuka',     cardName: 'Searching for Unseen Sights',                                type: 'speed',   rarity: 'SSR' },
    'silence-suzuka-speed':     { id: 'silence-suzuka-speed',     name: 'Silence Suzuka',     cardName: 'Beyond the Shining Scenery',                                 type: 'speed',   rarity: 'SSR' },
    'silence-suzuka-stamina':   { id: 'silence-suzuka-stamina',   name: 'Silence Suzuka',     cardName: 'Winning Dream',                                              type: 'stamina', rarity: 'SSR' },
    'smart-falcon-power':       { id: 'smart-falcon-power',       name: 'Smart Falcon',       cardName: 'My Umadol Way! ☆',                                           type: 'power',   rarity: 'SSR' },
    'special-week-guts':        { id: 'special-week-guts',        name: 'Special Week',       cardName: 'The Brightest Star in Japan!',                               type: 'guts',    rarity: 'SSR' },
    'special-week-speed':       { id: 'special-week-speed',       name: 'Special Week',       cardName: 'The Setting Sun and Rising Stars',                           type: 'speed',   rarity: 'SSR' },
    'super-creek-stamina':      { id: 'super-creek-stamina',      name: 'Super Creek',        cardName: 'Piece of Mind',                                              type: 'stamina', rarity: 'SSR' },
    'sweep-tosho-speed':        { id: 'sweep-tosho-speed',        name: 'Sweep Tosho',        cardName: 'It\'s All Mine!',                                            type: 'speed',   rarity: 'SSR' },
    'tamamo-cross-stamina':     { id: 'tamamo-cross-stamina',     name: 'Tamamo Cross',       cardName: 'Split the Sky, White Lightning!',                            type: 'stamina', rarity: 'SSR' },
    'tamamo-cross-power':       { id: 'tamamo-cross-power',       name: 'Tamamo Cross',       cardName: 'Beware! Halloween Night!',                                   type: 'power',   rarity: 'SSR' },
    'tazuna-hayakawa-pal':      { id: 'tazuna-hayakawa-pal',      name: 'Tazuna Hayakawa',    cardName: 'Tracen Reception',                                           type: 'pal',     rarity: 'SSR' },
    'tosen-jordan-speed':       { id: 'tosen-jordan-speed',       name: 'Tosen Jordan',       cardName: 'My Way',                                                     type: 'speed',   rarity: 'SSR' },
    'tokai-teio-speed':         { id: 'tokai-teio-speed',         name: 'Tokai Teio',         cardName: 'Dream Big!',                                                 type: 'speed',   rarity: 'SSR' },
    'twin-turbo-speed':         { id: 'twin-turbo-speed',         name: 'Twin Turbo',         cardName: 'Turbo Booooost',                                             type: 'speed',   rarity: 'SSR' },
    'vodka-power':              { id: 'vodka-power',              name: 'Vodka',              cardName: 'Wild Rider',                                                 type: 'power',   rarity: 'SSR' },
    'winning-ticket-guts':      { id: 'winning-ticket-guts',      name: 'Winning Ticket',     cardName: 'B・N・Winner!!',                                             type: 'guts',    rarity: 'SSR' },
    'winning-ticket-power':     { id: 'winning-ticket-power',     name: 'Winning Ticket',     cardName: 'Dreams Do Come True!',                                       type: 'power',   rarity: 'SSR' },
    'winning-ticket-stamina':   { id: 'winning-ticket-stamina',   name: 'Winning Ticket',     cardName: 'Full-Blown Tantrum',                                         type: 'stamina', rarity: 'SSR' },
    'yaeno-muteki-power':       { id: 'yaeno-muteki-power',       name: 'Yaeno Muteki',       cardName: 'Fiery Discipline',                                           type: 'power',   rarity: 'SSR' },
    'yukino-bijin-guts':        { id: 'yukino-bijin-guts',        name: 'Yukino Bijin',       cardName: 'Dancing Light into the Night',                               type: 'guts',    rarity: 'SSR' },
    'yukino-bijin-wit':         { id: 'yukino-bijin-wit',         name: 'Yukino Bijin',       cardName: 'Hometown Cheers',                                            type: 'wit',     rarity: 'SSR' },
    'zenno-rob-roy-speed':    { id: 'zenno-rob-roy-speed',    name: 'Zenno Rob Roy',      cardName: 'Magical Heroine',                                            type: 'speed', rarity: 'SSR' },
};

export const SUPPORT_CARD_LIST = Object.values(SUPPORT_CARD_DICT);

export const SUPPORT_CARD_TYPE_META: Record<SupportCardType, { label: string; color: string; bg: string }> = {
    speed:   { label: 'Speed',   color: 'text-sky-400',     bg: 'bg-sky-500/15'     },
    stamina: { label: 'Stamina', color: 'text-rose-400',    bg: 'bg-rose-500/15'    },
    power:   { label: 'Power',   color: 'text-orange-400',  bg: 'bg-orange-500/15'  },
    guts:    { label: 'Guts',    color: 'text-yellow-400',  bg: 'bg-yellow-500/15'  },
    wit:     { label: 'Wit',     color: 'text-emerald-400', bg: 'bg-emerald-500/15' },
    group:   { label: 'Group',   color: 'text-violet-400',  bg: 'bg-violet-500/15'  },
    pal:     { label: 'Pal',     color: 'text-fuchsia-400', bg: 'bg-fuchsia-500/15' },
};
